language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose -p aoc
  - cargo test --verbose -p aoc
  - cargo build --verbose
  - cargo test --verbose
