[package]
name = "rustvent"
version = "0.1.0"
authors = ["Anthony J Mirabella <a9@aneurysm9.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { version = "0.1.0", path = "aoc" }
structopt = "0.3"
